Repository brunomachadors/rpg-text-game, pull requests merged in 2023-08, with the labels that each got.

#3 Classes
  README.md
  attacks/weapons.js
  bin/textRPG.js
  challenges/doors.js
  characters/abilityScore.js
  characters/character.js
  characters/classes.js
  rolls/rolls.js
Labels: documentation, enhancement

#8 Class selected and character sheet displayed
  README.md
  bin/index.js
  challenges/textRPG.js
  characters/character.js
  gameText/gameTex.js
Labels: documentation, enhancement

#9 Attack system
  README.md
  attacks/attack.js
  attacks/weapons.js
  bin/index.js
  challenges/combat.js
  challenges/doors.js
  challenges/textRPG.js
  characters/abilityScore.js
  characters/character.js
  characters/classes.js
  characters/classes/cleric.js
  characters/classes/fighter.js
  characters/classes/rogue.js
  characters/classes/wizard.js
  gameText/gameTex.js
  rolls/rolls.js
Labels: bug, enhancement

#10 creating enemy model
  README.md
  challenges/doors.js
  challenges/monsters.js
  challenges/textRPG.js
Labels: bug, enhancement

#12 riddle challenge
  challenges/doors.js
  challenges/riddles.js
  gameText/gameTex.js
Labels: enhancement

#13 Combat system
  README.md
  attacks/weapons.js
  challenges/combat.js
  challenges/doors.js
  challenges/monsters.js
  challenges/riddles.js
  challenges/textRPG.js
  characters/character.js
  characters/classes/cleric.js
  characters/classes/fighter.js
  characters/classes/rogue.js
  characters/classes/wizard.js
  gameText/gameStatus.js
  gameText/gameTex.js
Labels: bug, enhancement

#14 Spells working
  README.md
  attacks/spellAttack.js
  attacks/weapons.js
  bin/index.js
  challenges/combat.js
  challenges/doors.js
  challenges/monsters.js
  challenges/riddles.js
  challenges/textRPG.js
  characters/character.js
  characters/classes/cleric.js
  characters/classes/fighter.js
  characters/classes/rogue.js
  characters/classes/wizard.js
  gameText/gameTex.js
  spells/arcaneSpells.js
Labels: bug, enhancement

#16 Trap Attack, Traps and Disable Trap
  README.md
  attacks/trapAttack.js
  attacks/weaponAttack.js
  challenges/combat.js
  challenges/doors.js
  challenges/monsters.js
  challenges/riddles.js
  challenges/textRPG.js
  challenges/traps.js
  challenges/treasureChest.js
  characters/character.js
  characters/classes/cleric.js
  characters/classes/fighter.js
  characters/classes/rogue.js
  characters/classes/wizard.js
  characters/skills/disabelTrap.js
  gameText/gameStatus.js
  gameText/gameText.js
  package-lock.json
  package.json
  timeouts.js
  yarn.lock
Labels: enhancement, help wanted

#18 sneak attack
  README.md
  attacks/sneakAttack.js
  attacks/trapAttack.js
  attacks/weapons.js
  challenges/combat.js
  challenges/doors.js
  challenges/monsters.js
  challenges/riddles.js
  challenges/textRPG.js
  challenges/traps.js
  challenges/treasureChest.js
  characters/character.js
  characters/classes/rogue.js
  characters/skills/disabelTrap.js
  characters/skills/stealth.js
  gameText/gameText.js
  helpers/timeouts.js
  rolls/rolls.js
Labels: bug, documentation, enhancement
